services:
  web:
    build: .
    container_name: web
    networks:
      - testing
    volumes:
      # - ./:/data
      - ./data:/app
      # Added new download directory
      - /mnt/docker_volume/flask_downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
#      - 8010:81
      - "127.0.0.1:8010:81"
      # - 5000:5000
    restart: unless-stopped
    command: waitress-serve --port 81 flask_web:app

networks:
  testing:
    external: true
