version: "3.9"
services:
  web:
    build: .
    container_name: web
    networks:
      - testing
    volumes:
      # - ./:/data
      - ./:/app
    ports:
#      - 8010:81
      - "127.0.0.1:8010:81"
      # - 5000:5000
    restart: unless-stopped
    command: waitress-serve --port 81 flask_web:app
    depends_on:
      - mariadb_flask
    
  mariadb_flask:
    image: lscr.io/linuxserver/mariadb:latest
    command: --skip-innodb-read-only-compressed
    container_name: mariadb_flask
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD=""}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - TZ=America/New_York
    networks:
      - testing
    volumes:
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

networks:
  testing:
    external: true
